web:
  build: .
  command: php -S 0.0.0.0:8080 -t /htdocs
  links:
    - db
  ports:
    - "8080:8080"
  volumes:
    - ./htdocs:/htdocs
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
